disabled_rules:
- trailing_whitespace
- multiline_function_chains
- identifier_name
- discarded_notification_center_observer
- notification_center_detachment
- orphaned_doc_comment
- unused_capture_list
- unused_optional_binding
- multiline_literal_brackets
- multiline_arguments
- multiline_parameters
- multiline_parameters_brackets
- discouraged_object_literal
- unneeded_parentheses_in_closure_argument
- pattern_matching_keywords
- array_init
- prefer_self_type_over_type_of_self
- todo
- multiple_closures_with_trailing_closure
- valid_ibinspectable
- attributes
- type_name

opt_in_rules:
- empty_count
- empty_string
- closure_end_indentation
- closure_spacing
- collection_alignment
- colon
- empty_collection_literal
- enum_case_associated_values_count
- fatal_error_message
- first_where
- force_unwrapping
- implicitly_unwrapped_optional
- last_where
- legacy_random
- literal_expression_end_indentation
- operator_usage_whitespace
- redundant_nil_coalescing
- redundant_type_annotation
- strict_fileprivate
- toggle_bool
- trailing_closure
- vertical_whitespace_closing_braces
- yoda_condition
- trailing_whitespace

analyzer_rules:
- unused_import

excluded:
- Carthage
- Pods
- DerivedData
- SwiftLint

#attributes:
#  always_on_same_line:
#    - "@IBSegueAction"
#    - "@IBAction"
#    - "@NSManaged"
#    - "@objc"

force_cast: warning
force_try: warning

line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 5
    error: 6
type_body_length:
    warning: 600
    error: 800
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

reporter: "xcode"
